InetApp/InetApp/Controllers/StockController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using InetApp.Models;
using System.Collections;

namespace InetApp.Controllers
{
    public class StockController : Controller
    {
        private StockContext db = new StockContext();

        public ActionResult Home()
        {
            ViewBag.Goods = db.Goods;
            return View();
        }

        public ActionResult Search(string searchTerm)
        {
            ViewBag.Goods = db.Goods;
            if (String.IsNullOrEmpty(searchTerm)) return Redirect("~/");
            var result = db.Depots.Where(w => w.Good_Name.Contains(searchTerm)).ToList();

            return View("Good", result);
        }

        //All goods
        public ActionResult Index()
        {
            ViewBag.Goods = db.Goods;
            return View(db.Depots);
        }

        //Вывод выбранного товара
        public ActionResult Good(int? goodId,int? Id,string Provider="",string Category="",string returnUrl="")
        {
            ViewBag.Goods = db.Goods;
            int argMask = 0 ;
            List<Depot> selectedItems = new List<Depot>();

            if (Id.HasValue)
            {
                try
                { 
                   selectedItems = db.Depots.Where(x => x.Id == Id).ToList();
                   return View(selectedItems);

                }
                catch (Exception e)
                {
                    return RedirectToAction("Error");
                }
            }
            else if (goodId.HasValue) argMask += 100;
            else if (!String.IsNullOrEmpty(Provider)) argMask += 10;
            else if (!String.IsNullOrEmpty(Category)) argMask += 1;

            try
            {
                switch (argMask)
                {
                    case 111:
                        selectedItems = db.Depots.Where(x => x.Good_id == goodId)
                           .Where(x => x.Category == Category)
                           .Where(x => x.Provider_Name == Provider)
                           .Where(x => x.Depot_Quantity > 0)
                           .ToList();
                        break;
                    case 110:
                        selectedItems = db.Depots.Where(x => x.Good_id == goodId)
                           .Where(x => x.Category == Category)
                           .Where(x => x.Depot_Quantity > 0)
                           .ToList();
                        break;
                    case 101:
                        selectedItems = db.Depots.Where(x => x.Good_id == goodId)
                           .Where(x => x.Provider_Name == Provider)
                           .Where(x => x.Depot_Quantity > 0)
                           .ToList();
                        break;
                    case 100:
                        selectedItems = db.Depots.Where(x => x.Good_id == goodId)
                            .Where(x => x.Depot_Quantity > 0)
                            .ToList();
                        break;
                    case 11:
                        selectedItems = db.Depots.Where(x => x.Category == Category)
                            .Where(x => x.Provider_Name == Provider)
                            .Where(x => x.Depot_Quantity > 0)
                            .ToList();
                        break;
                    case 10:
                        selectedItems = db.Depots.Where(x => x.Provider_Name == Provider)
                             .Where(x => x.Depot_Quantity > 0)
                             .ToList();
                        break;
                    case 1:
                        selectedItems = db.Depots.Where(x => x.Category == Category)
                              .Where(x => x.Depot_Quantity > 0)
                              .ToList();
                        break;
                    default:
                        selectedItems = db.Depots.ToList();
                        break;
                }
                if (selectedItems.Count == 0) 
                {
                    return RedirectToAction("Index");
                }
                return View(selectedItems);
            }
            catch (Exception e)
            {
                return RedirectToAction("Index");
            }
        }

        public ActionResult Error()
        {
            ViewBag.Goods = db.Goods;
            return View();
        }

    }
}

InetApp/InetApp/Views/Shared/_BuscketPartial.cshtml
@{
    ViewBag.Title = "_BuscketPartial";
    InetApp.Models.Cart cart = (InetApp.Models.Cart)HttpContext.Current.Session["Cart"];
}

<ul id="cart" class="dropdown">
    @if (cart != null)
{
    foreach (InetApp.Models.Pur_strings item in cart.Lines)
    {
        <li><a style="color: rgb(87,183,223); width:140px;">@item.Good.Good_Name : @item.Quantity</a></li>
    }
        <li><a style="color: rgb(87,183,223); width: 140px;">Total:@cart.TotalCost()</a></li>
}
    else
    {
        <li><a style="color: rgb(87,183,223); width: 140px;">Empty</a></li>
    }
    
</ul>


InetApp/InetApp/Views/Shared/_FooterPartial.cshtml
@{
    ViewBag.Title = "_FooterPartial";
}

<div class="footerbg">
    <!-- START Simpler footer -->
    <input type="checkbox" id="box1">
    <div class="border-menu">Footer</div>
    <ul id="footer">
        <li><a href="~/Stock/Home">Home</a></li>
        <li class="show-content">
            <a href="#">About Us</a><div class="tooltip">
                <h2>About US</h2><span>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam quis gravida turpis. Suspendisse luctus mollis odio, vel imperdiet neque vulputate in. Nullam a tincidunt lectus.
                    Nulla dignissim fermentum dolor sit amet bibendum. Etiam porta orci ut elit rhoncus, a sagittis tellus rhoncus..
                </span><span>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam quis gravida turpis. Suspendisse luctus mollis odio, vel imperdiet neque vulputate in. Nullam a tincidunt lectus.
                    Nulla dignissim fermentum dolor sit amet bibendum. Etiam porta orci ut elit rhoncus, a sagittis tellus rhoncus..
                </span>
            </div>
        </li>
        <li><a href="#">Services</a></li>
        <li><a href="#">Projects</a></li>
        <li class="show-content">
            <a href="#">Contact Us</a>
            <div class="tooltip">
                <h3>Contact</h3>
                <div id="form-div">
                    <form class="form" id="form1">

                        <p class="name">
                            <input name="name" type="text" class="validate[required,custom[onlyLetter],length[0,100]] feedback-input" placeholder="Name" id="name" />
                        </p>

                        <p class="email">
                            <input name="email" type="text" class="validate[required,custom[email]] feedback-input" id="email" placeholder="Email" />
                        </p>

                        <p class="text">
                            <textarea name="text" class="validate[required,length[6,300]] feedback-input" id="text" placeholder="Text"></textarea>
                        </p>

                        <input type="submit" value="Send" />
                    </form>
                </div>
            </div>
        </li>
        <li><a class="twitter" href="#">Twitter</a></li>
        <li><a class="facebook" href="#">Facebook</a></li>
        <li><a class="google" href="#">Google+</a></li>
        <li><a class="linkedin" href="#">Linkedin</a></li>
    </ul>
</div>

InetApp/InetApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - Buildein Stock</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <link href='http://fonts.googleapis.com/css?family=Changa+One' rel='stylesheet' type='text/css'>
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
            <div class="lk-panel">
                        @Html.Partial("_LoginPartial")
            </div>
                        @Html.Partial("_NavPartial")
        </header>
        <div id="body">
                @RenderBody()
        </div>
        <div id="FOOTER">
            @Html.Partial("_FooterPartial")
        </div>
        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>

InetApp/InetApp/Views/Shared/_NavPartial.cshtml
@{
    ViewBag.Title = "_HeaderPartial";
    IEnumerable<InetApp.Models.Good> Goods = ViewBag.Goods;
    var categories = Goods.GroupBy(x => x.Good_Category).Select(g => g.First()).ToList();
}
<div class="nav">
    <div class="nav-wrapper">
        <ul>
            <li><a href="~/Stock/Index">Categories:</a></li>

            @foreach (var category in categories)
            {
                <li class="parent">
                    @Html.ActionLink(category.Good_Category, "Good","Stock", new { Category = category.Good_Category }, null)
                    <ul class="dropdown">
                        @foreach (var item in Goods.Where(x => x.Good_Category == category.Good_Category))
                        {
                            <li>@Html.ActionLink(item.Good_Name, "Good", "Stock", new { goodId = item.Id }, null)</li>
                        }
                    </ul>
                </li>
            }
            <li id="bskt" class="parent">
                <a id="bskt-bkg" href="~/Cart/Index"></a>
                 @Html.Partial("_BuscketPartial")
            </li>
        </ul>
    </div>
</div>
